### ISSUE TITLE
NFS options incompatibility with Git 

### ISSUE THREAD

**Issue by lakano** [nanobox-io/nanobox-docker-unfs#19]
Hi,

If you try to run « git add README.md » inside a network_dir, there is a permission denied error, caused in theory of a disk full or a wrong permissions.
The permissions are correctly set, owned by gonano user, the disk isn't full, and a « git init » works correctly ( folder .git created )

If you try without the network_dirs option, this works correctly. This seems to be a bug in the NFS options, surely something to tweak to prevent this.

Currently, our company can't uses nanobox to host our Git repositories. 

After some researches and help from @danhunsaker we've discovered the problem come from incompatibility of NFS options with Git. 
We've found [this article from GitLab](https://docs.gitlab.com/ee/administration/high_availability/nfs.html) and this is a problem that could be solved from server/client options with NFSv4.

They recommend to use NFS v4 and the server options no_root_squash and sync, and the client options defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive

Could you please upgrade to NFSv4 and permit to use EVAR to customize server/clients options?

```
run.config:
    engine: nodejs
    extra_packages:
        - git

data.storage:
    image: nanobox/unfs:0.9

web.site:
    start: sleep 365d
    network_dirs:
        data.storage:
            - storage

```
Logs:
```
$ git add README.md 
fatal: error when closing sha1 file: Permission denied

```

Regards,
